// JavaScript Document

document.write('    <div id="header">');
document.write('     <div class="row_1">');
document.write('      <div class="col_1">');
document.write('       <div class="indent">');
document.write('        <h1>Mid-Coast Baptist Church</h1>');
document.write('       </div>');
document.write('      </div>');
document.write('      <div class="clear"></div>');
document.write('     </div>');
document.write('     <div class="row_2">');
document.write('      <!-- <img alt="" src="images/slogan.jpg" />-->');
document.write('      <div class="col_1">');
document.write('       <div class="top_margin">');
document.write('        <h3>Meeting at</h3>');
document.write('        <p>170 Old Portland Road<br />');
document.write('        Brunswick, Maine<br />');
document.write('        (207) 373-0818<br />');
document.write('        <a href="mailto:pastor@midcoastbaptistchurch.com">Email the Pastor</a></p><br /><br />');
document.write('        <h3>Schedule of Meetings</h3>');
document.write('        <p>Sunday School - 10:00am<br />');
document.write('        Morning Worship - 11:00am<br />');
document.write('        Evening Worship - 6:00pm<br />');
document.write('        Thursday - 7:00pm</p><br />');
document.write('        Daycare Provided for All Services<br /><br />');
document.write('        Children\'s Church during<br />Morning Worship');
document.write('       </div>');
document.write('      </div>');
document.write('     </div>');
document.write('     <div class="row_3">');
document.write('      <div class="indent">');
document.write('       <ul class="menu">');
document.write('        <li style="margin-left:45px"><a href="index.php">Home</a></li>');
document.write('        <li>');
document.write('            <a href="aboutus.php">About Us</a>');
document.write('            <ul>');
document.write('                <li><a href="pastors.php">Pastors</a></li>');
document.write('                <li><a href="doctrine.php">Doctrine</a></li>');
document.write('                <li><a href="ourhistory.php">Our History</a></li>');
document.write('                <li><a href="faqs.php">FAQs</a></li>');
document.write('            </ul>');
document.write('        </li>');
document.write('        <li>');
document.write('            <a href="media.php">Media</a>');
document.write('            <ul>');
document.write('                <li><a href="audio.php">Audio</a></li>');
document.write('                <li><a href="reading.php">Reading</a></li>');
document.write('            </ul>');
document.write('        </li>');
document.write('        <li><a href="thegospel.php">The Gospel</a></li>');
document.write('        <li>');
document.write('            <a href="missions.php">Missions</a>');
document.write('            <ul>');
document.write('                <li><a href="philosophy.php">Philosophy</a></li>');
document.write('                <li><a href="missionaries.php">Missionaries</a></li>');
document.write('            </ul>');
document.write('        </li>');
document.write('        <li><a href="contactus.php">Contact Us</a></li>');
document.write('       </ul>');
document.write('      </div>');
document.write('     </div>');
document.write('    </div>');